ERROR 2019-10-12 14:25:26,634 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:25:26,680 log 228 Bad Request: /
WARNING 2019-10-12 14:25:26,681 basehttp 124 "GET / HTTP/1.1" 400 69936
ERROR 2019-10-12 14:25:27,105 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:25:27,131 log 228 Bad Request: /favicon.ico
WARNING 2019-10-12 14:25:27,131 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 69858
INFO 2019-10-12 14:27:01,301 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-12 14:27:01,380 log 228 Not Found: /cart/
WARNING 2019-10-12 14:27:01,381 basehttp 124 "GET /cart/ HTTP/1.1" 404 1964
WARNING 2019-10-12 14:27:26,783 log 228 Not Found: /cart/
WARNING 2019-10-12 14:27:26,784 basehttp 124 "GET /cart/ HTTP/1.1" 404 1964
WARNING 2019-10-12 14:27:29,928 log 228 Not Found: /cart/
WARNING 2019-10-12 14:27:29,929 basehttp 124 "GET /cart/ HTTP/1.1" 404 1964
WARNING 2019-10-12 14:27:30,096 log 228 Not Found: /cart/
WARNING 2019-10-12 14:27:30,097 basehttp 124 "GET /cart/ HTTP/1.1" 404 1964
WARNING 2019-10-12 14:27:30,629 log 228 Not Found: /cart/
WARNING 2019-10-12 14:27:30,630 basehttp 124 "GET /cart/ HTTP/1.1" 404 1964
ERROR 2019-10-12 14:31:08,642 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:31:08,682 log 228 Bad Request: /
WARNING 2019-10-12 14:31:08,683 basehttp 124 "GET / HTTP/1.1" 400 69936
ERROR 2019-10-12 14:31:09,107 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:31:09,135 log 228 Bad Request: /favicon.ico
WARNING 2019-10-12 14:31:09,135 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 69858
ERROR 2019-10-12 14:33:11,503 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:33:11,542 log 228 Bad Request: /
WARNING 2019-10-12 14:33:11,542 basehttp 124 "GET / HTTP/1.1" 400 70092
ERROR 2019-10-12 14:33:11,633 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:33:11,661 log 228 Bad Request: /favicon.ico
WARNING 2019-10-12 14:33:11,661 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 70014
ERROR 2019-10-12 14:33:15,797 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:33:15,841 log 228 Bad Request: /
WARNING 2019-10-12 14:33:15,841 basehttp 124 "GET / HTTP/1.1" 400 70227
ERROR 2019-10-12 14:33:16,210 exception 77 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2019-10-12 14:33:16,233 log 228 Bad Request: /favicon.ico
WARNING 2019-10-12 14:33:16,234 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 70275
INFO 2019-10-12 14:34:15,490 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-10-12 14:34:15,543 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-10-12 14:34:15,649 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2019-10-12 14:34:15,650 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-10-12 14:34:15,650 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
WARNING 2019-10-12 14:34:15,655 log 228 Not Found: /favicon.ico
WARNING 2019-10-12 14:34:15,655 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 1977
INFO 2019-10-12 14:35:47,178 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-10-12 14:36:05,227 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-10-12 15:15:24,854 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-10-12 15:15:24,871 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-10-12 15:15:24,921 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:15:24,922 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:15:24,924 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:33:14,282 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2019-10-12 15:33:28,894 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2019-10-12 15:51:00,884 basehttp 124 "GET / HTTP/1.1" 200 16286
INFO 2019-10-12 15:51:00,897 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-10-12 15:51:00,988 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:51:00,991 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:51:00,991 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2019-10-12 15:51:01,004 basehttp 124 "GET /favicon.ico HTTP/1.1" 200 16286
INFO 2019-10-12 16:00:24,191 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2019-10-12 16:00:24,257 basehttp 124 "GET /cart/ HTTP/1.1" 200 16286
WARNING 2019-10-12 16:13:42,610 log 228 Not Found: /
WARNING 2019-10-12 16:13:42,611 basehttp 124 "GET / HTTP/1.1" 404 2114
WARNING 2019-10-12 16:13:42,647 log 228 Not Found: /favicon.ico
WARNING 2019-10-12 16:13:42,647 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2165
INFO 2019-10-12 16:13:56,602 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-12 16:13:56,649 log 228 Not Found: /cart/
WARNING 2019-10-12 16:13:56,650 basehttp 124 "GET /cart/ HTTP/1.1" 404 2152
WARNING 2019-10-12 16:13:57,421 log 228 Not Found: /cart/
WARNING 2019-10-12 16:13:57,422 basehttp 124 "GET /cart/ HTTP/1.1" 404 2152
ERROR 2019-10-12 16:13:58,323 log 228 Internal Server Error: /image_codes/b6ddb974-d136-440a-91de-ddc83941c650/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:13:58,324 basehttp 124 "GET /image_codes/b6ddb974-d136-440a-91de-ddc83941c650/ HTTP/1.1" 500 18824
ERROR 2019-10-12 16:13:59,200 log 228 Internal Server Error: /image_codes/46e2a918-f061-4765-8140-3d600916f840/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:13:59,201 basehttp 124 "GET /image_codes/46e2a918-f061-4765-8140-3d600916f840/ HTTP/1.1" 500 18824
ERROR 2019-10-12 16:14:00,322 log 228 Internal Server Error: /image_codes/88c9cafa-7943-4bac-b558-b0a4e15f5d3b/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:14:00,323 basehttp 124 "GET /image_codes/88c9cafa-7943-4bac-b558-b0a4e15f5d3b/ HTTP/1.1" 500 18824
ERROR 2019-10-12 16:14:19,090 log 228 Internal Server Error: /image_codes/5beb68b3-377d-4fe0-9782-97318b6e9ab1/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:14:19,091 basehttp 124 "GET /image_codes/5beb68b3-377d-4fe0-9782-97318b6e9ab1/ HTTP/1.1" 500 18824
ERROR 2019-10-12 16:15:08,771 log 228 Internal Server Error: /image_codes/9a76a712-ba9a-4a6a-9c31-47e994ff61b2/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:15:08,772 basehttp 124 "GET /image_codes/9a76a712-ba9a-4a6a-9c31-47e994ff61b2/ HTTP/1.1" 500 18824
INFO 2019-10-12 16:16:17,631 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-12 16:16:17,689 log 228 Not Found: /cart/
WARNING 2019-10-12 16:16:17,690 basehttp 124 "GET /cart/ HTTP/1.1" 404 2152
ERROR 2019-10-12 16:16:21,448 log 228 Internal Server Error: /image_codes/eca82098-70ae-475b-9f9f-bd35ab108dad/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:16:21,449 basehttp 124 "GET /image_codes/eca82098-70ae-475b-9f9f-bd35ab108dad/ HTTP/1.1" 500 18824
ERROR 2019-10-12 16:16:24,456 log 228 Internal Server Error: /image_codes/e6a7bf70-680e-4114-8691-a771f2de1aea/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:16:24,457 basehttp 124 "GET /image_codes/e6a7bf70-680e-4114-8691-a771f2de1aea/ HTTP/1.1" 500 18824
INFO 2019-10-12 16:17:29,838 basehttp 124 "GET /image_codes/(?P%3Cimage_code_id%3E.+)/$ HTTP/1.1" 301 0
ERROR 2019-10-12 16:17:29,895 log 228 Internal Server Error: /image_codes/(/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    text, image = captcha.generate_captcha()
ValueError: too many values to unpack (expected 2)
ERROR 2019-10-12 16:17:29,895 basehttp 124 "GET /image_codes/(/?P%3Cimage_code_id%3E.+)/$ HTTP/1.1" 500 95968
WARNING 2019-10-12 16:18:57,199 log 228 Not Found: /
WARNING 2019-10-12 16:18:57,199 basehttp 124 "GET / HTTP/1.1" 404 2114
WARNING 2019-10-12 16:19:34,249 log 228 Not Found: /
WARNING 2019-10-12 16:19:34,249 basehttp 124 "GET / HTTP/1.1" 404 2114
WARNING 2019-10-12 16:20:07,198 log 228 Not Found: /
WARNING 2019-10-12 16:20:07,198 basehttp 124 "GET / HTTP/1.1" 404 2008
INFO 2019-10-12 16:20:13,603 basehttp 124 "GET /image_codes/fa9a306f-ec57-47a8-86b2-90fbc7a6577c/ HTTP/1.1" 200 3534
WARNING 2019-10-14 09:39:48,988 log 228 Not Found: /
WARNING 2019-10-14 09:39:48,989 basehttp 124 "GET / HTTP/1.1" 404 2008
WARNING 2019-10-14 09:39:49,068 log 228 Not Found: /favicon.ico
WARNING 2019-10-14 09:39:49,068 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2059
WARNING 2019-10-14 09:40:13,451 log 228 Not Found: /image_codes
WARNING 2019-10-14 09:40:13,451 basehttp 124 "GET /image_codes HTTP/1.1" 404 2059
INFO 2019-10-14 09:40:32,202 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 09:40:32,315 log 228 Not Found: /cart/
WARNING 2019-10-14 09:40:32,316 basehttp 124 "GET /cart/ HTTP/1.1" 404 2046
WARNING 2019-10-14 09:40:33,278 log 228 Not Found: /cart/
WARNING 2019-10-14 09:40:33,279 basehttp 124 "GET /cart/ HTTP/1.1" 404 2046
INFO 2019-10-14 09:40:34,536 basehttp 124 "GET /image_codes/9ffd4c3c-6993-4dd8-b20f-cfdb4813c798/ HTTP/1.1" 200 3080
INFO 2019-10-14 09:40:36,014 basehttp 124 "GET /image_codes/4a45c879-0a1b-4a45-91e6-07767337dabe/ HTTP/1.1" 200 3211
INFO 2019-10-14 09:40:36,798 basehttp 124 "GET /image_codes/96574409-bd15-48c0-af5b-fba002b10910/ HTTP/1.1" 200 3009
INFO 2019-10-14 09:40:37,679 basehttp 124 "GET /image_codes/55b1775b-0441-4891-8dbf-487bec615629/ HTTP/1.1" 200 3502
INFO 2019-10-14 09:43:12,365 basehttp 124 "GET /image_codes/5c4a11e5-1d47-4e4c-bc1d-c4055d3e0238/ HTTP/1.1" 200 3532
INFO 2019-10-14 13:41:06,048 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 13:41:06,096 log 228 Not Found: /cart/
WARNING 2019-10-14 13:41:06,097 basehttp 124 "GET /cart/ HTTP/1.1" 404 2046
INFO 2019-10-14 13:41:09,410 basehttp 124 "GET /image_codes/dffa6e5f-fc08-4b73-b358-3af398d6d488/ HTTP/1.1" 200 3313
WARNING 2019-10-14 13:41:22,920 log 228 Not Found: /usernames/zzzzz/count/
WARNING 2019-10-14 13:41:22,921 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 404 2097
WARNING 2019-10-14 13:41:33,028 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:41:33,028 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 13:42:00,753 basehttp 124 "GET /image_codes/98f22528-fb19-40a4-af14-e2a7e9aa6b76/ HTTP/1.1" 200 3330
WARNING 2019-10-14 13:42:09,746 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:42:09,751 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:42:09,752 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:42:09,753 basehttp 124 "GET /sms_codes/15591483858/?text=mnqq&image_code_id=98f22528-fb19-40a4-af14-e2a7e9aa6b76 HTTP/1.1" 404 2162
INFO 2019-10-14 13:42:19,403 basehttp 124 "GET /image_codes/a610ef5d-aabc-4ba5-931a-261349d85be1/ HTTP/1.1" 200 3215
WARNING 2019-10-14 13:42:28,214 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:42:28,218 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:42:28,219 basehttp 124 "GET /sms_codes/15591483858/?text=gugz&image_code_id=a610ef5d-aabc-4ba5-931a-261349d85be1 HTTP/1.1" 404 2162
WARNING 2019-10-14 13:42:28,219 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:45:15,301 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:45:15,303 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:45:15,303 basehttp 124 "GET /sms_codes/15591483858/?text=gugz&image_code_id=a610ef5d-aabc-4ba5-931a-261349d85be1 HTTP/1.1" 404 2162
WARNING 2019-10-14 13:45:15,303 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 13:45:18,019 basehttp 124 "GET /image_codes/83273c37-08dd-4652-a7bd-35b7b135a2ae/ HTTP/1.1" 200 2943
WARNING 2019-10-14 13:45:25,258 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:45:25,261 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:45:25,262 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:45:25,263 basehttp 124 "GET /sms_codes/15591483858/?text=vami&image_code_id=83273c37-08dd-4652-a7bd-35b7b135a2ae HTTP/1.1" 404 2162
INFO 2019-10-14 13:48:01,463 basehttp 124 "GET /image_codes/04a64556-97c2-4cd1-9dd5-06c584a041cc/ HTTP/1.1" 200 3322
WARNING 2019-10-14 13:48:05,315 log 228 Not Found: /usernames/zzzzz/count/
WARNING 2019-10-14 13:48:05,317 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 404 2097
WARNING 2019-10-14 13:48:13,805 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:13,806 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 13:48:13,895 basehttp 124 "GET /image_codes/22625c41-6654-4d2d-aa5c-38e43f44fe25/ HTTP/1.1" 200 3233
INFO 2019-10-14 13:48:15,099 basehttp 124 "GET /image_codes/87008b34-b16f-4d19-acf4-74a1807f82bd/ HTTP/1.1" 200 3185
WARNING 2019-10-14 13:48:20,083 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:20,086 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:20,087 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:20,087 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:21,218 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:21,221 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:21,222 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:21,222 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:23,006 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:23,008 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:23,009 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:23,009 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:23,453 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:23,455 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:23,459 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:23,460 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:23,640 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:23,640 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:23,646 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:23,647 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:25,407 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:25,412 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:25,412 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:25,413 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:35,845 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:35,851 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:35,851 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:35,852 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:42,703 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:42,705 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:42,709 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:42,710 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:43,842 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:43,843 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:43,846 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:43,846 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:48,958 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:48,962 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:48,963 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:48,965 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:49,582 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:49,587 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:49,587 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:49,588 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:48:52,825 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:48:52,829 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:48:52,830 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:48:52,830 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:50:11,526 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:50:11,527 basehttp 124 "GET /sms_codes/15591483858/?text=urk9&image_code_id=87008b34-b16f-4d19-acf4-74a1807f82bd HTTP/1.1" 404 2162
WARNING 2019-10-14 13:50:11,528 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:50:11,529 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 13:50:40,570 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 13:50:40,620 log 228 Not Found: /cart/
WARNING 2019-10-14 13:50:40,620 basehttp 124 "GET /cart/ HTTP/1.1" 404 2046
INFO 2019-10-14 13:50:53,979 basehttp 124 "GET /image_codes/405029e6-37b6-466f-8aa1-8a481923241c/ HTTP/1.1" 200 3388
WARNING 2019-10-14 13:51:07,705 log 228 Not Found: /usernames/11111/count/
WARNING 2019-10-14 13:51:07,706 basehttp 124 "GET /usernames/11111/count/ HTTP/1.1" 404 2097
WARNING 2019-10-14 13:51:17,958 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:51:17,959 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 13:51:18,055 basehttp 124 "GET /image_codes/9ef5e06e-13c4-47f8-b5d8-eda2e7d30b12/ HTTP/1.1" 200 2778
WARNING 2019-10-14 13:51:24,754 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:51:24,756 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
WARNING 2019-10-14 13:51:24,760 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:51:24,760 basehttp 124 "GET /sms_codes/15591483858/?text=twgh&image_code_id=9ef5e06e-13c4-47f8-b5d8-eda2e7d30b12 HTTP/1.1" 404 2162
WARNING 2019-10-14 13:51:31,823 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 13:51:31,827 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 13:51:31,827 basehttp 124 "GET /sms_codes/15591483858/?text=twgh&image_code_id=9ef5e06e-13c4-47f8-b5d8-eda2e7d30b12 HTTP/1.1" 404 2162
WARNING 2019-10-14 13:51:31,828 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2109
INFO 2019-10-14 16:13:46,593 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 16:13:46,671 log 228 Not Found: /cart/
WARNING 2019-10-14 16:13:46,672 basehttp 124 "GET /cart/ HTTP/1.1" 404 2243
INFO 2019-10-14 16:13:48,184 basehttp 124 "GET /image_codes/093c56b6-b9d7-44fb-8958-fdaa377ef2c2/ HTTP/1.1" 200 3413
WARNING 2019-10-14 16:13:54,230 log 228 Not Found: /usernames/11111/count/
WARNING 2019-10-14 16:13:54,230 basehttp 124 "GET /usernames/11111/count/ HTTP/1.1" 404 2294
WARNING 2019-10-14 16:14:03,527 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:14:03,527 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2306
WARNING 2019-10-14 16:14:07,428 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:14:07,433 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 16:14:07,434 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2306
WARNING 2019-10-14 16:14:07,434 basehttp 124 "GET /sms_codes/15591483858/?text=sc7h&image_code_id=093c56b6-b9d7-44fb-8958-fdaa377ef2c2 HTTP/1.1" 404 2359
INFO 2019-10-14 16:16:52,558 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 16:16:52,630 log 228 Not Found: /cart/
WARNING 2019-10-14 16:16:52,630 basehttp 124 "GET /cart/ HTTP/1.1" 404 2243
WARNING 2019-10-14 16:17:14,386 log 228 Not Found: /cart/
WARNING 2019-10-14 16:17:14,387 basehttp 124 "GET /cart/ HTTP/1.1" 404 2243
INFO 2019-10-14 16:17:15,536 basehttp 124 "GET /image_codes/05c97cae-fbde-47ca-bfaa-bf13818249ca/ HTTP/1.1" 200 3291
INFO 2019-10-14 16:18:15,226 basehttp 124 "GET /image_codes/de14053b-5599-4e1c-ad70-99dc1aa54c21/ HTTP/1.1" 200 2880
INFO 2019-10-14 16:18:26,698 basehttp 124 "GET /image_codes/8303da61-4d07-4f61-b0eb-bdf448d4538a/ HTTP/1.1" 200 3101
INFO 2019-10-14 16:40:51,252 basehttp 124 "GET /image_codes/dd80fff7-2dd7-47de-989f-8f0c579ca87a/ HTTP/1.1" 200 2986
WARNING 2019-10-14 16:40:55,490 log 228 Not Found: /usernames/11111/count/
WARNING 2019-10-14 16:40:55,491 basehttp 124 "GET /usernames/11111/count/ HTTP/1.1" 404 2263
WARNING 2019-10-14 16:41:03,823 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:41:03,823 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2275
WARNING 2019-10-14 16:41:09,002 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:41:09,008 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 16:41:09,009 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2275
WARNING 2019-10-14 16:41:09,009 basehttp 124 "GET /sms_codes/15591483858/?text=3icj&image_code_id=dd80fff7-2dd7-47de-989f-8f0c579ca87a HTTP/1.1" 404 2328
WARNING 2019-10-14 16:43:07,445 log 228 Not Found: /
WARNING 2019-10-14 16:43:07,445 basehttp 124 "GET / HTTP/1.1" 404 2187
WARNING 2019-10-14 16:43:07,820 log 228 Not Found: /favicon.ico
WARNING 2019-10-14 16:43:07,820 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2238
INFO 2019-10-14 16:43:15,582 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 16:43:15,623 log 228 Not Found: /cart/
WARNING 2019-10-14 16:43:15,623 basehttp 124 "GET /cart/ HTTP/1.1" 404 2225
WARNING 2019-10-14 16:43:19,740 log 228 Not Found: /cart/
WARNING 2019-10-14 16:43:19,740 basehttp 124 "GET /cart/ HTTP/1.1" 404 2225
INFO 2019-10-14 16:43:20,637 basehttp 124 "GET /image_codes/bc50ae1c-86c2-4d45-adfd-a8ade83feb1c/ HTTP/1.1" 200 3221
WARNING 2019-10-14 16:43:22,923 log 228 Not Found: /usernames/11111/count/
WARNING 2019-10-14 16:43:22,923 basehttp 124 "GET /usernames/11111/count/ HTTP/1.1" 404 2276
WARNING 2019-10-14 16:43:32,647 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:43:32,647 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:43:37,519 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:43:37,522 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 16:43:37,699 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'mobile'
ERROR 2019-10-14 16:43:37,701 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 500 18814
WARNING 2019-10-14 16:44:27,413 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:44:27,415 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 16:44:27,461 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 67, in get
    send_sms_code.delay(mobile, sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 16:44:27,463 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 500 24741
WARNING 2019-10-14 16:46:52,490 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:46:52,493 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:46:52,500 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 16:46:52,501 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 400 49
WARNING 2019-10-14 16:47:25,547 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:47:25,548 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 16:47:25,548 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 400 49
WARNING 2019-10-14 16:47:25,549 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:47:44,204 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:47:44,208 log 228 Not Found: /sms_codes/15591483858/
WARNING 2019-10-14 16:47:44,209 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2294
WARNING 2019-10-14 16:47:44,209 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 404 2347
WARNING 2019-10-14 16:54:11,844 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:54:11,847 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:54:11,853 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 16:54:11,853 basehttp 124 "GET /sms_codes/15591483858/?text=zx3v&image_code_id=bc50ae1c-86c2-4d45-adfd-a8ade83feb1c HTTP/1.1" 400 49
INFO 2019-10-14 16:54:14,220 basehttp 124 "GET /image_codes/f6b328cb-a9cd-4d40-8b89-862bcea87d40/ HTTP/1.1" 200 2789
WARNING 2019-10-14 16:54:28,638 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:54:28,643 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 16:54:28,644 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:54:28,645 basehttp 124 "GET /sms_codes/15591483858/?text=41ze&image_code_id=f6b328cb-a9cd-4d40-8b89-862bcea87d40 HTTP/1.1" 400 46
WARNING 2019-10-14 16:54:33,334 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:54:33,335 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 16:54:33,387 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 67, in get
    send_sms_code.delay(mobile, sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 16:54:33,389 basehttp 124 "GET /sms_codes/15591483858/?text=4ize&image_code_id=f6b328cb-a9cd-4d40-8b89-862bcea87d40 HTTP/1.1" 500 24741
WARNING 2019-10-14 16:56:45,769 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:56:45,770 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 16:56:45,775 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 16:56:45,776 basehttp 124 "GET /sms_codes/15591483858/?text=4ize&image_code_id=f6b328cb-a9cd-4d40-8b89-862bcea87d40 HTTP/1.1" 400 49
INFO 2019-10-14 16:56:49,428 basehttp 124 "GET /image_codes/48f2c4f2-0d85-4056-8530-a3bee5afbadd/ HTTP/1.1" 200 3277
WARNING 2019-10-14 16:56:54,493 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:56:54,494 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 16:56:54,548 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 67, in get
    send_sms_code.delay(mobile, sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 16:56:54,550 basehttp 124 "GET /sms_codes/15591483858/?text=wvpc&image_code_id=48f2c4f2-0d85-4056-8530-a3bee5afbadd HTTP/1.1" 500 24741
INFO 2019-10-14 16:59:42,464 basehttp 124 "GET /image_codes/5506cb97-f4ff-4a94-9da7-1cb247375b06/ HTTP/1.1" 200 3562
WARNING 2019-10-14 16:59:47,500 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 16:59:47,501 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 16:59:47,555 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 67, in get
    send_sms_code.delay(mobile, sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 16:59:47,557 basehttp 124 "GET /sms_codes/15591483858/?text=qych&image_code_id=5506cb97-f4ff-4a94-9da7-1cb247375b06 HTTP/1.1" 500 24741
WARNING 2019-10-14 17:00:58,410 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:00:58,413 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:00:58,420 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:00:58,420 basehttp 124 "GET /sms_codes/15591483858/?text=qych&image_code_id=5506cb97-f4ff-4a94-9da7-1cb247375b06 HTTP/1.1" 400 49
INFO 2019-10-14 17:02:45,440 basehttp 124 "GET /image_codes/2cf8708b-4888-4f84-baa6-18158202b42b/ HTTP/1.1" 200 3093
WARNING 2019-10-14 17:02:57,071 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:02:57,072 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
ERROR 2019-10-14 17:02:57,119 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 68, in get
    print(send_sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 167, in __str__
    return str(self._get_current_object())
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 17:02:57,121 basehttp 124 "GET /sms_codes/15591483858/?text=acsx&image_code_id=2cf8708b-4888-4f84-baa6-18158202b42b HTTP/1.1" 500 24710
WARNING 2019-10-14 17:03:07,601 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:03:07,602 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:03:07,608 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:03:07,608 basehttp 124 "GET /sms_codes/15591483858/?text=acsx&image_code_id=2cf8708b-4888-4f84-baa6-18158202b42b HTTP/1.1" 400 49
INFO 2019-10-14 17:03:10,134 basehttp 124 "GET /image_codes/d5d61d5e-bf95-48ff-b806-2f5c4e975005/ HTTP/1.1" 200 2942
INFO 2019-10-14 17:03:11,830 basehttp 124 "GET /image_codes/b7fb4271-28b9-4731-819d-f08a5ccf9c55/ HTTP/1.1" 200 3279
WARNING 2019-10-14 17:03:20,178 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:03:20,182 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:03:20,183 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:03:20,184 basehttp 124 "GET /sms_codes/15591483858/?text=syuf&image_code_id=b7fb4271-28b9-4731-819d-f08a5ccf9c55 HTTP/1.1" 400 55
INFO 2019-10-14 17:03:46,066 basehttp 124 "GET /image_codes/6bd4a171-8b66-4d2a-b192-56eac8f7ed6a/ HTTP/1.1" 200 3020
WARNING 2019-10-14 17:03:51,955 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:03:51,959 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:03:51,960 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:03:51,962 basehttp 124 "GET /sms_codes/15591483858/?text=t7i8&image_code_id=6bd4a171-8b66-4d2a-b192-56eac8f7ed6a HTTP/1.1" 400 55
INFO 2019-10-14 17:04:16,320 basehttp 124 "GET /image_codes/f541d529-5f63-460e-b686-086a37d512aa/ HTTP/1.1" 200 3258
WARNING 2019-10-14 17:04:31,020 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:04:31,025 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:04:31,027 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:04:31,027 basehttp 124 "GET /sms_codes/15591483858/?text=msdk&image_code_id=f541d529-5f63-460e-b686-086a37d512aa HTTP/1.1" 400 46
INFO 2019-10-14 17:05:18,287 basehttp 124 "GET /image_codes/facfd678-80c4-4ae5-b14e-e67984b40bf4/ HTTP/1.1" 200 3065
WARNING 2019-10-14 17:05:22,422 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:05:22,424 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
INFO 2019-10-14 17:05:22,426 basehttp 124 "GET /sms_codes/15591483858/?text=ersg&image_code_id=facfd678-80c4-4ae5-b14e-e67984b40bf4 HTTP/1.1" 200 16
INFO 2019-10-14 17:06:23,269 basehttp 124 "GET /image_codes/fcf472a1-0f61-4e20-a564-2b648f14c6b8/ HTTP/1.1" 200 3436
WARNING 2019-10-14 17:06:27,897 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:06:27,898 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
INFO 2019-10-14 17:06:27,900 basehttp 124 "GET /sms_codes/15591483858/?text=rrqp&image_code_id=fcf472a1-0f61-4e20-a564-2b648f14c6b8 HTTP/1.1" 200 16
INFO 2019-10-14 17:07:20,158 basehttp 124 "GET /image_codes/b2b30c90-4e1c-4d05-ad12-143186e13439/ HTTP/1.1" 200 3338
WARNING 2019-10-14 17:07:28,567 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:07:28,568 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:07:28,572 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:07:28,572 basehttp 124 "GET /sms_codes/15591483858/?text=mhw8&image_code_id=b2b30c90-4e1c-4d05-ad12-143186e13439 HTTP/1.1" 400 46
INFO 2019-10-14 17:07:30,045 basehttp 124 "GET /image_codes/26c65fa4-b22e-485f-a106-3f70318e9867/ HTTP/1.1" 200 3295
WARNING 2019-10-14 17:07:34,502 log 228 Not Found: /mobiles/15591483858/count/
WARNING 2019-10-14 17:07:34,506 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 404 2288
INFO 2019-10-14 17:07:34,508 basehttp 124 "GET /sms_codes/15591483858/?text=69rp&image_code_id=26c65fa4-b22e-485f-a106-3f70318e9867 HTTP/1.1" 200 16
INFO 2019-10-14 17:08:32,623 basehttp 124 "GET /image_codes/d6f3cad2-a594-4752-86a8-6ee4469cb7f2/ HTTP/1.1" 200 3066
WARNING 2019-10-14 17:08:36,756 log 228 Not Found: /usernames/156156548q/count/
WARNING 2019-10-14 17:08:36,756 basehttp 124 "GET /usernames/156156548q/count/ HTTP/1.1" 404 2291
WARNING 2019-10-14 17:08:51,918 log 228 Not Found: /mobiles/13919555222/count/
WARNING 2019-10-14 17:08:51,918 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 404 2288
WARNING 2019-10-14 17:09:01,439 log 228 Not Found: /mobiles/13919555222/count/
WARNING 2019-10-14 17:09:01,443 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 404 2288
INFO 2019-10-14 17:09:01,446 basehttp 124 "GET /sms_codes/13919555222/?text=niyy&image_code_id=d6f3cad2-a594-4752-86a8-6ee4469cb7f2 HTTP/1.1" 200 16
INFO 2019-10-14 17:09:33,131 basehttp 124 "GET /image_codes/2d4e7086-fc9f-4db2-bf72-167d9e811536/ HTTP/1.1" 200 3586
INFO 2019-10-14 17:09:37,146 basehttp 124 "GET /usernames/154845252255/count/ HTTP/1.1" 200 37
INFO 2019-10-14 17:09:48,800 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 200 34
WARNING 2019-10-14 17:09:53,192 log 228 Bad Request: /sms_codes/13919555222/
WARNING 2019-10-14 17:09:53,193 basehttp 124 "GET /sms_codes/13919555222/?text=wrop&image_code_id=2d4e7086-fc9f-4db2-bf72-167d9e811536 HTTP/1.1" 400 55
INFO 2019-10-14 17:09:53,196 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:09:55,828 basehttp 124 "GET /image_codes/9d03adf7-b848-4fcf-9c80-261ce75fb77c/ HTTP/1.1" 200 3032
WARNING 2019-10-14 17:10:00,797 log 228 Bad Request: /sms_codes/13919555222/
WARNING 2019-10-14 17:10:00,798 basehttp 124 "GET /sms_codes/13919555222/?text=a8yj&image_code_id=9d03adf7-b848-4fcf-9c80-261ce75fb77c HTTP/1.1" 400 55
INFO 2019-10-14 17:10:00,801 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:10:02,406 basehttp 124 "GET /image_codes/81cfb67f-0b03-47ca-a278-135fafc0b5e4/ HTTP/1.1" 200 3405
INFO 2019-10-14 17:10:07,388 basehttp 124 "GET /sms_codes/13919555222/?text=phor&image_code_id=81cfb67f-0b03-47ca-a278-135fafc0b5e4 HTTP/1.1" 200 16
INFO 2019-10-14 17:10:07,392 basehttp 124 "GET /mobiles/13919555222/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:11:06,486 basehttp 124 "GET /image_codes/e561395d-e69b-4d51-9109-4591b466ede9/ HTTP/1.1" 200 3377
INFO 2019-10-14 17:11:09,620 basehttp 124 "GET /usernames/15654884/count/ HTTP/1.1" 200 33
INFO 2019-10-14 17:11:28,793 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:11:34,282 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
ERROR 2019-10-14 17:11:34,331 log 228 Internal Server Error: /sms_codes/15591483858/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 317, in _get_current_object
    return object.__getattribute__(self, '__thing')
AttributeError: 'PromiseProxy' object has no attribute '__thing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 144, in _smart_import
    return imp(path)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 67, in get
    send_sms_code.delay(mobile, sms_code)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 319, in _get_current_object
    return self.__evaluate__()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 349, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 459, in _task_from_fun
    task.bind(self)  # connects task to this app
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/task.py", line 338, in bind
    setattr(cls, attr_name, conf[config_name])
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 437, in __getitem__
    return getitem(k)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/collections.py", line 286, in __getitem__
    return mapping[_key]
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/collections/__init__.py", line 1021, in __getitem__
    if key in self.data:
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 141, in data
    return self.callback()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 935, in _finalize_pending_conf
    conf = self._conf = self._load_config()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/app/base.py", line 945, in _load_config
    self.loader.config_from_object(self._config_source)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 126, in config_from_object
    obj = self._smart_import(obj, imp=self.import_from_cwd)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 147, in _smart_import
    return symbol_by_name(path, imp=imp)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 98, in import_from_cwd
    package=package,
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery_tasks'
ERROR 2019-10-14 17:11:34,333 basehttp 124 "GET /sms_codes/15591483858/?text=ioro&image_code_id=e561395d-e69b-4d51-9109-4591b466ede9 HTTP/1.1" 500 24741
WARNING 2019-10-14 17:11:38,432 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:11:38,433 basehttp 124 "GET /sms_codes/15591483858/?text=ioro&image_code_id=e561395d-e69b-4d51-9109-4591b466ede9 HTTP/1.1" 400 49
INFO 2019-10-14 17:11:38,438 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:11:39,702 basehttp 124 "GET /image_codes/19f842d4-fe7b-4875-9453-961158a8e94e/ HTTP/1.1" 200 3308
WARNING 2019-10-14 17:11:50,177 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:11:50,179 basehttp 124 "GET /sms_codes/15591483858/?text=zrad&image_code_id=19f842d4-fe7b-4875-9453-961158a8e94e HTTP/1.1" 400 55
INFO 2019-10-14 17:11:50,182 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:11:52,050 basehttp 124 "GET /image_codes/b8ab31ce-9d5e-4ccc-9191-e17630275070/ HTTP/1.1" 200 3029
WARNING 2019-10-14 17:11:56,349 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:11:56,349 basehttp 124 "GET /sms_codes/15591483858/?text=auac&image_code_id=b8ab31ce-9d5e-4ccc-9191-e17630275070 HTTP/1.1" 400 55
INFO 2019-10-14 17:11:56,353 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:11:57,377 basehttp 124 "GET /image_codes/094a9870-91ff-401e-9871-17640185c0fd/ HTTP/1.1" 200 3259
WARNING 2019-10-14 17:12:01,845 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:12:01,846 basehttp 124 "GET /sms_codes/15591483858/?text=xxbw&image_code_id=094a9870-91ff-401e-9871-17640185c0fd HTTP/1.1" 400 55
INFO 2019-10-14 17:12:01,849 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:12:13,148 basehttp 124 "GET /image_codes/94cb42e4-bbd1-4b77-9d14-e9ee90228891/ HTTP/1.1" 200 3392
INFO 2019-10-14 17:12:13,496 basehttp 124 "GET /image_codes/05bf1823-3ed9-4412-a917-9cf7e6e4f2d8/ HTTP/1.1" 200 3535
WARNING 2019-10-14 17:12:18,526 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:12:18,527 basehttp 124 "GET /sms_codes/15591483858/?text=izla&image_code_id=05bf1823-3ed9-4412-a917-9cf7e6e4f2d8 HTTP/1.1" 400 55
INFO 2019-10-14 17:12:18,531 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:16:23,239 basehttp 124 "GET /image_codes/6dc34936-7ae6-44de-9784-094b8e0fa461/ HTTP/1.1" 200 3068
INFO 2019-10-14 17:16:28,780 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:16:28,861 basehttp 124 "GET /sms_codes/15591483858/?text=93zy&image_code_id=6dc34936-7ae6-44de-9784-094b8e0fa461 HTTP/1.1" 200 16
INFO 2019-10-14 17:19:46,013 basehttp 124 "GET /image_codes/34c2ee1c-96f5-4947-88eb-dd6be5769ed2/ HTTP/1.1" 200 3448
INFO 2019-10-14 17:19:53,468 basehttp 124 "GET /sms_codes/15591483858/?text=gcjp&image_code_id=34c2ee1c-96f5-4947-88eb-dd6be5769ed2 HTTP/1.1" 200 16
INFO 2019-10-14 17:19:53,471 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:20:56,179 basehttp 124 "GET /image_codes/953bfb1d-b51e-44cd-bc01-5cf386b8fce6/ HTTP/1.1" 200 3030
WARNING 2019-10-14 17:21:02,638 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 17:21:02,640 basehttp 124 "GET /sms_codes/15591483858/?text=kgs7&image_code_id=953bfb1d-b51e-44cd-bc01-5cf386b8fce6 HTTP/1.1" 400 46
INFO 2019-10-14 17:21:02,643 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:21:03,746 basehttp 124 "GET /image_codes/4f5a4fa0-4ea6-4251-bfc2-a23d2fdb3747/ HTTP/1.1" 200 3025
INFO 2019-10-14 17:21:11,472 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:21:11,554 basehttp 124 "GET /sms_codes/15591483858/?text=o7jn&image_code_id=4f5a4fa0-4ea6-4251-bfc2-a23d2fdb3747 HTTP/1.1" 200 16
INFO 2019-10-14 17:23:33,850 basehttp 124 "GET /image_codes/d2519eb3-976e-41e0-954b-acbed67f05e9/ HTTP/1.1" 200 3556
INFO 2019-10-14 17:23:39,690 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 17:23:39,774 basehttp 124 "GET /sms_codes/15591483858/?text=hn5f&image_code_id=d2519eb3-976e-41e0-954b-acbed67f05e9 HTTP/1.1" 200 16
INFO 2019-10-14 17:24:04,242 basehttp 124 "GET /image_codes/a6021ea6-2028-4609-a329-cf38946f8005/ HTTP/1.1" 200 2741
WARNING 2019-10-14 17:50:53,430 log 228 Not Found: /
WARNING 2019-10-14 17:50:53,430 basehttp 124 "GET / HTTP/1.1" 404 2575
WARNING 2019-10-14 17:50:53,784 log 228 Not Found: /favicon.ico
WARNING 2019-10-14 17:50:53,785 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2626
INFO 2019-10-14 17:51:12,274 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 17:51:12,328 log 228 Not Found: /cart/
WARNING 2019-10-14 17:51:12,328 basehttp 124 "GET /cart/ HTTP/1.1" 404 2613
WARNING 2019-10-14 17:51:13,651 log 228 Not Found: /cart/
WARNING 2019-10-14 17:51:13,652 basehttp 124 "GET /cart/ HTTP/1.1" 404 2613
INFO 2019-10-14 17:51:15,189 basehttp 124 "GET /image_codes/962be78c-b160-4e00-a565-8810e14c012d/ HTTP/1.1" 200 3541
INFO 2019-10-14 18:26:42,391 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-14 18:26:42,452 log 228 Not Found: /cart/
WARNING 2019-10-14 18:26:42,452 basehttp 124 "GET /cart/ HTTP/1.1" 404 2613
INFO 2019-10-14 18:27:00,232 basehttp 124 "GET /image_codes/f55c2f2d-f09f-4117-9dc0-cfc786c0d655/ HTTP/1.1" 200 3252
INFO 2019-10-14 18:27:04,409 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-14 18:27:15,801 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 18:27:20,026 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 18:27:20,111 basehttp 124 "GET /sms_codes/15591483858/?text=w7ka&image_code_id=f55c2f2d-f09f-4117-9dc0-cfc786c0d655 HTTP/1.1" 200 16
INFO 2019-10-14 18:30:16,055 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
WARNING 2019-10-14 18:30:16,058 log 228 Bad Request: /sms_codes/15591483858/
WARNING 2019-10-14 18:30:16,059 basehttp 124 "GET /sms_codes/15591483858/?text=w7ka&image_code_id=f55c2f2d-f09f-4117-9dc0-cfc786c0d655 HTTP/1.1" 400 49
INFO 2019-10-14 18:30:17,324 basehttp 124 "GET /image_codes/e1b467ab-745c-409a-a6b1-53d5da1a4c6e/ HTTP/1.1" 200 3301
INFO 2019-10-14 18:30:24,168 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 18:30:24,255 basehttp 124 "GET /sms_codes/15591483858/?text=id8g&image_code_id=e1b467ab-745c-409a-a6b1-53d5da1a4c6e HTTP/1.1" 200 16
INFO 2019-10-14 18:34:05,011 basehttp 124 "GET /image_codes/cdd48e2c-36db-4ba9-b8e1-46ac42696995/ HTTP/1.1" 200 3193
INFO 2019-10-14 18:34:11,271 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-14 18:34:11,353 basehttp 124 "GET /sms_codes/15591483858/?text=3jrb&image_code_id=cdd48e2c-36db-4ba9-b8e1-46ac42696995 HTTP/1.1" 200 16
INFO 2019-10-15 11:55:54,838 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-15 11:55:55,075 log 228 Not Found: /cart/
WARNING 2019-10-15 11:55:55,075 basehttp 124 "GET /cart/ HTTP/1.1" 404 2766
WARNING 2019-10-15 11:56:15,056 log 228 Not Found: /cart/
WARNING 2019-10-15 11:56:15,056 basehttp 124 "GET /cart/ HTTP/1.1" 404 2766
INFO 2019-10-15 11:56:15,917 basehttp 124 "GET /image_codes/6bea72c2-2c8d-4d2d-97b1-99a3ee935c9c/ HTTP/1.1" 200 3271
INFO 2019-10-15 11:56:25,019 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-15 11:56:37,460 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-15 11:56:37,525 basehttp 124 "GET /image_codes/08a6a6c9-2413-4da9-baf1-12f38bbf7e16/ HTTP/1.1" 200 3272
INFO 2019-10-15 11:56:46,644 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-15 11:56:46,725 basehttp 124 "GET /sms_codes/15591483858/?text=8zjm&image_code_id=08a6a6c9-2413-4da9-baf1-12f38bbf7e16 HTTP/1.1" 200 16
INFO 2019-10-15 11:57:10,935 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
WARNING 2019-10-15 11:57:10,945 log 228 Not Found: /users/
WARNING 2019-10-15 11:57:10,948 basehttp 124 "POST /users/ HTTP/1.1" 404 2770
INFO 2019-10-15 11:57:10,950 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-15 11:57:10,951 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
WARNING 2019-10-15 11:57:12,946 log 228 Not Found: /users/
WARNING 2019-10-15 11:57:12,951 basehttp 124 "POST /users/ HTTP/1.1" 404 2770
INFO 2019-10-15 11:57:12,955 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-15 11:57:12,958 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
WARNING 2019-10-15 11:57:19,527 log 228 Not Found: /users/
WARNING 2019-10-15 11:57:19,528 basehttp 124 "POST /users/ HTTP/1.1" 404 2770
INFO 2019-10-15 11:57:19,531 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-15 11:57:19,531 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-15 11:58:31,566 basehttp 124 "GET /usernames/zzzzz/count/ HTTP/1.1" 200 30
INFO 2019-10-15 11:58:31,570 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-15 11:58:31,820 basehttp 124 "POST /users/ HTTP/1.1" 201 222
INFO 2019-10-15 14:13:47,078 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2019-10-15 14:13:47,090 log 228 Not Found: /authorizations/
WARNING 2019-10-15 14:13:47,090 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2798
INFO 2019-10-15 14:18:36,475 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2019-10-15 14:18:36,659 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-15 14:18:36,695 log 228 Not Found: /cart/
WARNING 2019-10-15 14:18:36,695 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:18:51,610 log 228 Bad Request: /authorizations/
WARNING 2019-10-15 14:18:51,610 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2019-10-15 14:18:55,865 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 14:18:56,029 log 228 Not Found: /cart/
WARNING 2019-10-15 14:18:56,029 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:57:19,102 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-15 14:57:19,158 log 228 Not Found: /cart/
WARNING 2019-10-15 14:57:19,158 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:57:23,137 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-10-15 14:57:23,232 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 14:57:23,388 log 228 Not Found: /cart/
WARNING 2019-10-15 14:57:23,388 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:57:23,871 log 228 Not Found: /cart/
WARNING 2019-10-15 14:57:23,872 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:57:31,806 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 14:57:31,950 log 228 Not Found: /cart/
WARNING 2019-10-15 14:57:31,951 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:57:35,666 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
WARNING 2019-10-15 14:57:35,671 log 228 Not Found: /user/
WARNING 2019-10-15 14:57:35,672 basehttp 124 "GET /user/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:57:42,299 log 228 Not Found: /areas/
WARNING 2019-10-15 14:57:42,302 basehttp 124 "GET /areas/ HTTP/1.1" 404 2933
INFO 2019-10-15 14:57:42,300 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2019-10-15 14:57:42,350 log 228 Not Found: /addresses/
WARNING 2019-10-15 14:57:42,351 basehttp 124 "GET /addresses/ HTTP/1.1" 404 2945
WARNING 2019-10-15 14:58:12,039 log 228 Not Found: /user/
WARNING 2019-10-15 14:58:12,040 basehttp 124 "GET /user/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:58:18,626 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 14:58:18,805 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:18,806 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:20,411 log 228 Not Found: /user/
WARNING 2019-10-15 14:58:20,412 basehttp 124 "GET /user/ HTTP/1.1" 404 2930
INFO 2019-10-15 14:58:25,323 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 14:58:25,482 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:25,483 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:29,899 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:29,900 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:30,740 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:30,740 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:31,590 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:31,591 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:32,190 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:32,191 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:33,958 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:33,959 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
WARNING 2019-10-15 14:58:35,388 log 228 Not Found: /cart/
WARNING 2019-10-15 14:58:35,389 basehttp 124 "GET /cart/ HTTP/1.1" 404 2930
INFO 2019-10-15 15:34:40,028 basehttp 124 "GET /image_codes/54168dcf-6279-48c4-b034-d99edb320aa8/ HTTP/1.1" 200 3122
INFO 2019-10-15 15:34:48,754 basehttp 124 "GET /image_codes/14faccc2-8a55-4ef1-9e25-c64afece783b/ HTTP/1.1" 200 3081
INFO 2019-10-15 15:34:54,898 basehttp 124 "GET /accounts/zzzzz/sms/token/?text=xitp&image_code_id=14faccc2-8a55-4ef1-9e25-c64afece783b HTTP/1.1" 200 185
INFO 2019-10-15 15:34:57,992 basehttp 124 "GET /sms_codes/?access_token=eyJhbGciOiJIUzI1NiIsImlhdCI6MTU3MTEyNDg5NCwiZXhwIjoxNTcxMTI1MTk0fQ.eyJtb2JpbGUiOiIxNTU5MTQ4Mzg1OCJ9.mIZ9YgqQl93jKWfoIRA3ZAmIJoaWb-JXcljplX82hGI HTTP/1.1" 200 16
INFO 2019-10-15 15:35:09,723 basehttp 124 "GET /accounts/zzzzz/password/token/?sms_code=644535 HTTP/1.1" 200 160
INFO 2019-10-15 15:35:22,574 basehttp 124 "OPTIONS /users/1/password/ HTTP/1.1" 200 0
INFO 2019-10-15 15:35:22,744 basehttp 124 "POST /users/1/password/ HTTP/1.1" 200 8
INFO 2019-10-15 15:38:23,313 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 15:38:23,487 log 228 Not Found: /cart/
WARNING 2019-10-15 15:38:23,487 basehttp 124 "GET /cart/ HTTP/1.1" 404 3664
WARNING 2019-10-15 15:38:24,124 log 228 Not Found: /cart/
WARNING 2019-10-15 15:38:24,125 basehttp 124 "GET /cart/ HTTP/1.1" 404 3664
WARNING 2019-10-15 15:38:33,010 log 228 Bad Request: /authorizations/
WARNING 2019-10-15 15:38:33,011 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2019-10-15 15:38:37,988 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 15:38:38,161 log 228 Not Found: /cart/
WARNING 2019-10-15 15:38:38,161 basehttp 124 "GET /cart/ HTTP/1.1" 404 3664
WARNING 2019-10-15 15:38:40,238 log 228 Not Found: /cart/
WARNING 2019-10-15 15:38:40,239 basehttp 124 "GET /cart/ HTTP/1.1" 404 3664
INFO 2019-10-15 15:38:57,419 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-15 15:38:57,592 log 228 Not Found: /cart/
WARNING 2019-10-15 15:38:57,593 basehttp 124 "GET /cart/ HTTP/1.1" 404 3664
INFO 2019-10-16 10:10:30,043 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-16 10:10:30,203 log 228 Not Found: /cart/
WARNING 2019-10-16 10:10:30,204 basehttp 124 "GET /cart/ HTTP/1.1" 404 3817
INFO 2019-10-16 10:10:40,842 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-10-16 10:10:40,853 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2019-10-16 10:10:40,889 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2019-10-16 10:10:40,898 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 10:10:40,899 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3853
INFO 2019-10-16 10:10:54,823 basehttp 124 "GET /user/ HTTP/1.1" 200 82
WARNING 2019-10-16 10:10:54,836 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 10:10:54,837 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3853
WARNING 2019-10-16 10:49:19,129 log 228 Not Found: /cart/
WARNING 2019-10-16 10:49:19,129 basehttp 124 "GET /cart/ HTTP/1.1" 404 3817
WARNING 2019-10-16 10:49:24,839 log 228 Not Found: /cart/
WARNING 2019-10-16 10:49:24,840 basehttp 124 "GET /cart/ HTTP/1.1" 404 3817
INFO 2019-10-16 10:49:26,301 basehttp 124 "GET /image_codes/e1c85fe2-8e42-4bf9-acc6-f92c833c0140/ HTTP/1.1" 200 3132
INFO 2019-10-16 10:49:29,307 basehttp 124 "GET /usernames/15591483858/count/ HTTP/1.1" 200 36
INFO 2019-10-16 10:49:32,750 basehttp 124 "GET /usernames/11111/count/ HTTP/1.1" 200 30
INFO 2019-10-16 10:49:42,302 basehttp 124 "GET /mobiles/15591483858/count/ HTTP/1.1" 200 34
INFO 2019-10-16 10:49:53,360 basehttp 124 "GET /mobiles/15591483859/count/ HTTP/1.1" 200 34
INFO 2019-10-16 10:49:53,486 basehttp 124 "GET /mobiles/15591483859/count/ HTTP/1.1" 200 34
INFO 2019-10-16 10:49:53,943 basehttp 124 "GET /sms_codes/15591483859/?text=lau9&image_code_id=e1c85fe2-8e42-4bf9-acc6-f92c833c0140 HTTP/1.1" 200 16
INFO 2019-10-16 11:32:01,467 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-16 11:32:01,526 log 228 Not Found: /cart/
WARNING 2019-10-16 11:32:01,526 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
WARNING 2019-10-16 11:32:02,047 log 228 Not Found: /cart/
WARNING 2019-10-16 11:32:02,048 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 11:32:09,037 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-10-16 11:32:09,132 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2019-10-16 11:32:09,289 log 228 Not Found: /cart/
WARNING 2019-10-16 11:32:09,290 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
WARNING 2019-10-16 11:32:09,660 log 228 Not Found: /cart/
WARNING 2019-10-16 11:32:09,661 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 11:32:11,724 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-10-16 11:32:11,743 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2019-10-16 11:32:11,754 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2019-10-16 11:32:11,762 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 11:32:11,762 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
INFO 2019-10-16 11:32:59,492 basehttp 124 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2019-10-16 11:32:59,768 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/generics.py", line 228, in put
    return self.update(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/mixins.py", line 70, in update
    self.perform_update(serializer)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/mixins.py", line 80, in perform_update
    serializer.save()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/serializers.py", line 209, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/users/serializers.py", line 201, in update
    send_verify_email.delay(instance.email, verify_url)
NameError: name 'send_verify_email' is not defined
ERROR 2019-10-16 11:32:59,770 basehttp 124 "PUT /emails/ HTTP/1.1" 500 20116
ERROR 2019-10-16 11:33:02,546 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/generics.py", line 228, in put
    return self.update(request, *args, **kwargs)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/mixins.py", line 70, in update
    self.perform_update(serializer)
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/mixins.py", line 80, in perform_update
    serializer.save()
  File "/home/zjj/.virtualenvs/django_project/lib/python3.7/site-packages/rest_framework/serializers.py", line 209, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/zjj/PycharmProjects/django_project/meiduo_project/meiduo_mall/meiduo_mall/apps/users/serializers.py", line 201, in update
    send_verify_email.delay(instance.email, verify_url)
NameError: name 'send_verify_email' is not defined
ERROR 2019-10-16 11:33:02,547 basehttp 124 "PUT /emails/ HTTP/1.1" 500 20116
INFO 2019-10-16 11:43:35,973 basehttp 124 "PUT /emails/ HTTP/1.1" 200 35
INFO 2019-10-16 11:57:59,218 basehttp 124 "GET /user/ HTTP/1.1" 200 98
WARNING 2019-10-16 11:57:59,238 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 11:57:59,238 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
INFO 2019-10-16 11:58:00,466 basehttp 124 "PUT /emails/ HTTP/1.1" 200 35
INFO 2019-10-16 11:58:10,295 basehttp 124 "GET /user/ HTTP/1.1" 200 98
WARNING 2019-10-16 11:58:10,312 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 11:58:10,313 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
WARNING 2019-10-16 11:58:58,226 log 228 Not Found: /cart/
WARNING 2019-10-16 11:58:58,226 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 11:59:00,159 basehttp 124 "GET /user/ HTTP/1.1" 200 98
WARNING 2019-10-16 11:59:00,167 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 11:59:00,168 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
WARNING 2019-10-16 13:47:56,788 tasks 29 发送验证码短信[失败][ mobile: 15591483859 ]
INFO 2019-10-16 13:48:34,646 basehttp 124 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2019-10-16 13:48:34,807 basehttp 124 "PUT /emails/ HTTP/1.1" 200 35
INFO 2019-10-16 13:55:16,200 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-16 13:55:16,238 log 228 Not Found: /cart/
WARNING 2019-10-16 13:55:16,238 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 13:55:18,333 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-10-16 13:55:18,349 basehttp 124 "GET /user/ HTTP/1.1" 200 98
INFO 2019-10-16 13:55:18,361 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2019-10-16 13:55:18,367 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 13:55:18,368 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
INFO 2019-10-16 13:55:19,568 basehttp 124 "PUT /emails/ HTTP/1.1" 200 35
INFO 2019-10-16 13:56:05,491 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-10-16 13:56:05,586 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 226
WARNING 2019-10-16 13:56:05,760 log 228 Not Found: /cart/
WARNING 2019-10-16 13:56:05,760 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
WARNING 2019-10-16 13:56:06,242 log 228 Not Found: /cart/
WARNING 2019-10-16 13:56:06,243 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 13:56:07,122 basehttp 124 "GET /user/ HTTP/1.1" 200 98
WARNING 2019-10-16 13:56:07,137 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 13:56:07,137 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
INFO 2019-10-16 13:56:13,390 basehttp 124 "PUT /emails/ HTTP/1.1" 200 35
INFO 2019-10-16 13:56:52,903 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzI1NiIsImlhdCI6MTU3MTIwNTM3MywiZXhwIjoxNTcxMjA1NjczfQ.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6IjM3Njk3MTc4N0BxcS5jb20ifQ._Oycmp6BbObp9L4OHaTD7qHJSueL9YyBbGxocOjbr38 HTTP/1.1" 200 16
INFO 2019-10-16 13:56:59,216 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-10-16 13:56:59,253 log 228 Not Found: /cart/
WARNING 2019-10-16 13:56:59,254 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
WARNING 2019-10-16 13:57:00,250 log 228 Not Found: /cart/
WARNING 2019-10-16 13:57:00,251 basehttp 124 "GET /cart/ HTTP/1.1" 404 4140
INFO 2019-10-16 13:57:09,221 basehttp 124 "GET /user/ HTTP/1.1" 200 97
WARNING 2019-10-16 13:57:09,236 log 228 Not Found: /browse_histories/
WARNING 2019-10-16 13:57:09,237 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4176
